#!/usr/bin/env python
# coding: utf-8
''' apexlog
Script to summarise APEX html observing logs.
'''
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import with_statement
import argparse
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import re
from os.path import expanduser
from getpass import getuser
from glob import glob


def read_sourcecat(cat=None):
    '''Parse APEX source catalogue (.cat)

    Parameters
    ----------
    cat : string (optional)
        name of source catalogue, defaults to ~/'user'.cat

    Returns
    -------
    sci_sources : list
        Names of science sources
    '''

    sci_sources = []
    if cat is None:
        cat = expanduser('~/') + getuser() + '.cat'
    elif not cat.endswith('.cat'):
        cat = cat + '.cat'

    print('Reading science sources from:', cat)
    with open(cat) as f:
        s = f.readlines()
    for line in s:
        if ((line[0] != '!') & (line[0] != '\n') & (line[0] != ' ')):
            sci_sources.append(line.split()[0])
    return sci_sources


def read_linecat(cat=None):
    '''Parse APEX line cat .lin

    Parameters
    ----------
    cat : string (optional)
        name of line catalogue, defaults to ~/'user'.lin

    Returns
    -------
    sci_lines : dict
        Dictionary of science lines / frequencies
    '''
    sci_lines = []
    sci_freqs = []
    if cat is None:
        cat = expanduser('~/') + getuser() + '.lin'
    elif not cat.endswith('.lin'):
        cat = cat + '.lin'

    print('Reading science lines from:', cat)
    with open(cat) as f:
        s = f.readlines()
    for line in s:
        if ((line[0] != '!') & (line[0] != '\n') & (line[0] != ' ')):
            sci_lines.append(line.split()[0])
            sci_freqs.append(float(line.split()[1]))
    sci_lines = dict(zip(sci_lines, sci_freqs))
    return sci_lines


def read_one_log(filename):
    '''Read a html obslog to pandas DataFrame

    Parameters
    ----------
    filename : string
        obslog html file

    Returns
    -------
    df : pandas.DataFrame
        The obslog data
    '''

    print('Reading obslog:', filename)
    df = pd.read_html(filename, header=0)[0]
    df['UTC'] = pd.to_datetime(df.UTC, format='%Y-%m-%dU%H:%M:%S')
    df['Scan duration'] = pd.to_timedelta(df['Scan duration'], unit='s')
    df.drop(df[(df.Source == 'PARK') | (df.Source == 'ZENITH')].index,
            inplace=True)
    df['mm PWV'] = df[['mm PWV']].apply(pd.to_numeric)
    return df


def get_line_name(string):
    '''Get first white spaced delimited part of string'''
    return string.split()[0]


def read_obslogs(dir=None):
    '''Read APEX html obslogs

    Parameters
    ----------
    dir : string (optional)
        Directory with html log files, defaults to ~/obslogs/

    Returns
    -------
    df : pandas.DataFrame
        The obslog data
    '''

    if dir is None:
        dir = expanduser('~/obslogs/')
    logs = glob(dir + '*.html')

    print('')
    df = read_one_log(logs[0])
    for log in logs[1:]:
        df = pd.concat([df, read_one_log(log)], axis=0)
    df['Line'] = df['Mol. line'].apply(get_line_name)
    df.rename(columns=(lambda x: re.sub('[().]', '', x)), inplace=True)
    df.rename(columns=(lambda x: re.sub('[ -]', '_', x)), inplace=True)
    df.rename(columns=(lambda x: x.lower()), inplace=True)
    df.set_index('utc', inplace=True)
    df.sort_index(inplace=True)
    df.reset_index(inplace=True)
    return df


def summarise_sciobs(sci_sources, sci_lines, df):
    '''Summarise science observations in DataFrame

    Parameters
    ----------
    sci_sources : list
        List of science sources
    sci_lines : list/dict
        List or dictionary of science lines
    df : pandas.DataFrame
        The obslog data

    Returns
    -------
    dfs : pandas.DataFrame
        Summary of scan duration [min] for sources/lines
    '''

    print('\nSummarising scan duration by science sources/lines:')
    on_types = ['ONOFF', 'OTF']
    dfs = pd.DataFrame(df[df.source.isin(sci_sources)
                          & df.line.isin(sci_lines)
                          & df.scan_type.isin(on_types)
                          ]
                       )
    dfs = dfs.groupby(['source', 'line'])[['scan_duration']].sum()
    dfs['Duration [min]'] = (dfs['scan_duration'] /
                             np.timedelta64(1, 'm')).round(1)
    return dfs[['Duration [min]']]


def parse_inputs():
    '''Parse optional catalogs and obslogs dir'''
    parser = argparse.ArgumentParser(
        description='Summarises APEX obslogs, defaults to APEX account')
    parser.add_argument('-c', '--catalogs', type=str,
                        help='Location/basename of source and line catalogs')
    parser.add_argument('-o', '--obslogs', type=str,
                        help='Location of html obslogs')
    args = parser.parse_args()
    return args.catalogs, args.obslogs


def plot_dfs(dfs):
    dfs[['Duration [min]']].iloc[::-1].plot.barh(zorder=2, legend=False)
    plt.grid(zorder=0)
    plt.title('Sum of "ON" science source/line scan duration')
    plt.xlabel('Duration [min]')
    plt.savefig('apexlog.png', bbox_inches='tight')
    print('\nCreated plot: ./apexlog.png')
    return plt.gcf()


def main():
    catalogs, obslogs = parse_inputs()
    if (catalogs is None) & (obslogs is None):
        print('\033[1;32mDefaulting to APEX account:',
              '~/' + getuser() + '.[cat/lin] and ~/obslogs/\033[0m')
    sci_sources = read_sourcecat(catalogs)
    sci_lines = read_linecat(catalogs)
    df = read_obslogs(obslogs)
    dfs = summarise_sciobs(sci_sources, sci_lines, df)
    print(dfs)
    plot_dfs(dfs)
    return sci_sources, sci_lines, df, dfs


if __name__ == '__main__':
    sci_sources, sci_lines, df, dfs = main()

    # --- Example 1: List science source scans today and sum of on time
    # df.set_index('utc', inplace=True)
    # date = str(pd.datetime.utcnow().date())
    # date = '2016-12-10'
    # today = pd.DataFrame(df[(df.source.isin(sci_sources))
    #                         & (df.line.isin(sci_lines))][date])
    # print('\n', date, today['scan_duration'].sum())
    # print('Observed: ' + date)
    # print(today.source.value_counts())

    # --- Example 2: List which dates sources have been observed
    # df.set_index('utc', inplace=True)
    # sci = pd.DataFrame(df[(df.source.isin(sci_sources))
    #                       & (df.line.isin(sci_lines))])
    # print(sci.groupby(sci.index.date).source.unique())

    # --- Example 3: Running script locally
    # apexlog -c ~/APEX/projects/JellyFish/e-098.b-0657a-2016
    # -o ~/APEX/projects/JellyFish/obslogs/
